/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AppSettings {
  'dailyLimit' : [] | [number],
  'updatedAt' : bigint,
  'currency' : string,
  'weeklyLimit' : [] | [number],
}
export interface BackupRecord {
  'data' : string,
  'name' : string,
  'createdAt' : bigint,
}
export interface Category {
  'id' : string,
  'name' : string,
  'color' : string,
  'pinned' : [] | [boolean],
  'budget' : number,
}
export interface CategorySummary {
  'categoryId' : string,
  'total' : number,
  'categoryName' : string,
}
export interface DebtRecord {
  'id' : string,
  'status' : string,
  'direction' : string,
  'createdAt' : bigint,
  'dueDate' : [] | [string],
  'description' : string,
  'personName' : string,
  'amount' : number,
}
export interface Expense {
  'id' : string,
  'categoryId' : string,
  'paymentMethod' : string,
  'date' : string,
  'note' : string,
  'createdAt' : bigint,
  'amount' : number,
}
export interface ExpenseMeta {
  'receiptUrl' : [] | [string],
  'tags' : [] | [string],
}
export interface IncomeSource {
  'id' : string,
  'monthlyBudget' : number,
  'name' : string,
  'color' : string,
}
export interface MonthlyIncome { 'month' : string, 'amount' : number }
export interface MonthlySummary {
  'month' : string,
  'categoryBreakdown' : Array<CategorySummary>,
  'totalIncome' : number,
  'totalExpenses' : number,
}
export interface ShoppingItem {
  'id' : string,
  'estimatedPrice' : [] | [number],
  'date' : [] | [string],
  'name' : string,
  'createdAt' : bigint,
  'bought' : boolean,
  'category' : string,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControl' : ActorMethod<[], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'clearBoughtShoppingItems' : ActorMethod<[], undefined>,
  'createCategory' : ActorMethod<[Category], undefined>,
  'createExpense' : ActorMethod<[Expense], undefined>,
  'createShoppingItem' : ActorMethod<[ShoppingItem], undefined>,
  'deleteBackup' : ActorMethod<[string], undefined>,
  'deleteCategory' : ActorMethod<[string], undefined>,
  'deleteExpense' : ActorMethod<[string], undefined>,
  'deleteExpenseMeta' : ActorMethod<[string], undefined>,
  'deleteShoppingItem' : ActorMethod<[string], undefined>,
  'exportExpenses' : ActorMethod<[], Array<Expense>>,
  'getAppSettings' : ActorMethod<[], [] | [AppSettings]>,
  'getBackupsList' : ActorMethod<[], Array<BackupRecord>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCategories' : ActorMethod<[], Array<Category>>,
  'getDebts' : ActorMethod<[], Array<DebtRecord>>,
  'getExpenseMetaList' : ActorMethod<[], Array<[string, ExpenseMeta]>>,
  'getExpenses' : ActorMethod<[], Array<Expense>>,
  'getExpensesByCategory' : ActorMethod<[string], Array<Expense>>,
  'getExpensesByMonth' : ActorMethod<[string], Array<Expense>>,
  'getIncomeSourcesList' : ActorMethod<[], Array<IncomeSource>>,
  'getMonthlyIncome' : ActorMethod<[string], [] | [MonthlyIncome]>,
  'getMonthlySummary' : ActorMethod<[string], MonthlySummary>,
  'getShoppingItems' : ActorMethod<[], Array<ShoppingItem>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'resetUserData' : ActorMethod<[], undefined>,
  'saveBackup' : ActorMethod<[string, string], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'saveDebts' : ActorMethod<[Array<DebtRecord>], undefined>,
  'saveIncomeSources' : ActorMethod<[Array<IncomeSource>], undefined>,
  'setAppSettings' : ActorMethod<[AppSettings], undefined>,
  'setExpenseMeta' : ActorMethod<[string, ExpenseMeta], undefined>,
  'setMonthlyIncome' : ActorMethod<[MonthlyIncome], undefined>,
  'toggleShoppingItemBought' : ActorMethod<[string, boolean], undefined>,
  'updateCategory' : ActorMethod<[Category], undefined>,
  'updateExpense' : ActorMethod<[Expense], undefined>,
  'updateShoppingItem' : ActorMethod<[ShoppingItem], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];