/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Category = IDL.Record({
  'id' : IDL.Text,
  'name' : IDL.Text,
  'color' : IDL.Text,
  'pinned' : IDL.Opt(IDL.Bool),
  'budget' : IDL.Float64,
});
export const Expense = IDL.Record({
  'id' : IDL.Text,
  'categoryId' : IDL.Text,
  'paymentMethod' : IDL.Text,
  'date' : IDL.Text,
  'note' : IDL.Text,
  'createdAt' : IDL.Int,
  'amount' : IDL.Float64,
});
export const ShoppingItem = IDL.Record({
  'id' : IDL.Text,
  'estimatedPrice' : IDL.Opt(IDL.Float64),
  'date' : IDL.Opt(IDL.Text),
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'bought' : IDL.Bool,
  'category' : IDL.Text,
});
export const AppSettings = IDL.Record({
  'dailyLimit' : IDL.Opt(IDL.Float64),
  'updatedAt' : IDL.Int,
  'currency' : IDL.Text,
  'weeklyLimit' : IDL.Opt(IDL.Float64),
});
export const BackupRecord = IDL.Record({
  'data' : IDL.Text,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const DebtRecord = IDL.Record({
  'id' : IDL.Text,
  'status' : IDL.Text,
  'direction' : IDL.Text,
  'createdAt' : IDL.Int,
  'dueDate' : IDL.Opt(IDL.Text),
  'description' : IDL.Text,
  'personName' : IDL.Text,
  'amount' : IDL.Float64,
});
export const ExpenseMeta = IDL.Record({
  'receiptUrl' : IDL.Opt(IDL.Text),
  'tags' : IDL.Opt(IDL.Text),
});
export const IncomeSource = IDL.Record({
  'id' : IDL.Text,
  'monthlyBudget' : IDL.Float64,
  'name' : IDL.Text,
  'color' : IDL.Text,
});
export const MonthlyIncome = IDL.Record({
  'month' : IDL.Text,
  'amount' : IDL.Float64,
});
export const CategorySummary = IDL.Record({
  'categoryId' : IDL.Text,
  'total' : IDL.Float64,
  'categoryName' : IDL.Text,
});
export const MonthlySummary = IDL.Record({
  'month' : IDL.Text,
  'categoryBreakdown' : IDL.Vec(CategorySummary),
  'totalIncome' : IDL.Float64,
  'totalExpenses' : IDL.Float64,
});

export const idlService = IDL.Service({
  '_initializeAccessControl' : IDL.Func([], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'clearBoughtShoppingItems' : IDL.Func([], [], []),
  'createCategory' : IDL.Func([Category], [], []),
  'createExpense' : IDL.Func([Expense], [], []),
  'createShoppingItem' : IDL.Func([ShoppingItem], [], []),
  'deleteBackup' : IDL.Func([IDL.Text], [], []),
  'deleteCategory' : IDL.Func([IDL.Text], [], []),
  'deleteExpense' : IDL.Func([IDL.Text], [], []),
  'deleteExpenseMeta' : IDL.Func([IDL.Text], [], []),
  'deleteShoppingItem' : IDL.Func([IDL.Text], [], []),
  'exportExpenses' : IDL.Func([], [IDL.Vec(Expense)], ['query']),
  'getAppSettings' : IDL.Func([], [IDL.Opt(AppSettings)], ['query']),
  'getBackupsList' : IDL.Func([], [IDL.Vec(BackupRecord)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCategories' : IDL.Func([], [IDL.Vec(Category)], ['query']),
  'getDebts' : IDL.Func([], [IDL.Vec(DebtRecord)], ['query']),
  'getExpenseMetaList' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Text, ExpenseMeta))],
      ['query'],
    ),
  'getExpenses' : IDL.Func([], [IDL.Vec(Expense)], ['query']),
  'getExpensesByCategory' : IDL.Func([IDL.Text], [IDL.Vec(Expense)], ['query']),
  'getExpensesByMonth' : IDL.Func([IDL.Text], [IDL.Vec(Expense)], ['query']),
  'getIncomeSourcesList' : IDL.Func([], [IDL.Vec(IncomeSource)], ['query']),
  'getMonthlyIncome' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(MonthlyIncome)],
      ['query'],
    ),
  'getMonthlySummary' : IDL.Func([IDL.Text], [MonthlySummary], ['query']),
  'getShoppingItems' : IDL.Func([], [IDL.Vec(ShoppingItem)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'resetUserData' : IDL.Func([], [], []),
  'saveBackup' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'saveDebts' : IDL.Func([IDL.Vec(DebtRecord)], [], []),
  'saveIncomeSources' : IDL.Func([IDL.Vec(IncomeSource)], [], []),
  'setAppSettings' : IDL.Func([AppSettings], [], []),
  'setExpenseMeta' : IDL.Func([IDL.Text, ExpenseMeta], [], []),
  'setMonthlyIncome' : IDL.Func([MonthlyIncome], [], []),
  'toggleShoppingItemBought' : IDL.Func([IDL.Text, IDL.Bool], [], []),
  'updateCategory' : IDL.Func([Category], [], []),
  'updateExpense' : IDL.Func([Expense], [], []),
  'updateShoppingItem' : IDL.Func([ShoppingItem], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Category = IDL.Record({
    'id' : IDL.Text,
    'name' : IDL.Text,
    'color' : IDL.Text,
    'pinned' : IDL.Opt(IDL.Bool),
    'budget' : IDL.Float64,
  });
  const Expense = IDL.Record({
    'id' : IDL.Text,
    'categoryId' : IDL.Text,
    'paymentMethod' : IDL.Text,
    'date' : IDL.Text,
    'note' : IDL.Text,
    'createdAt' : IDL.Int,
    'amount' : IDL.Float64,
  });
  const ShoppingItem = IDL.Record({
    'id' : IDL.Text,
    'estimatedPrice' : IDL.Opt(IDL.Float64),
    'date' : IDL.Opt(IDL.Text),
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'bought' : IDL.Bool,
    'category' : IDL.Text,
  });
  const AppSettings = IDL.Record({
    'dailyLimit' : IDL.Opt(IDL.Float64),
    'updatedAt' : IDL.Int,
    'currency' : IDL.Text,
    'weeklyLimit' : IDL.Opt(IDL.Float64),
  });
  const BackupRecord = IDL.Record({
    'data' : IDL.Text,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const DebtRecord = IDL.Record({
    'id' : IDL.Text,
    'status' : IDL.Text,
    'direction' : IDL.Text,
    'createdAt' : IDL.Int,
    'dueDate' : IDL.Opt(IDL.Text),
    'description' : IDL.Text,
    'personName' : IDL.Text,
    'amount' : IDL.Float64,
  });
  const ExpenseMeta = IDL.Record({
    'receiptUrl' : IDL.Opt(IDL.Text),
    'tags' : IDL.Opt(IDL.Text),
  });
  const IncomeSource = IDL.Record({
    'id' : IDL.Text,
    'monthlyBudget' : IDL.Float64,
    'name' : IDL.Text,
    'color' : IDL.Text,
  });
  const MonthlyIncome = IDL.Record({
    'month' : IDL.Text,
    'amount' : IDL.Float64,
  });
  const CategorySummary = IDL.Record({
    'categoryId' : IDL.Text,
    'total' : IDL.Float64,
    'categoryName' : IDL.Text,
  });
  const MonthlySummary = IDL.Record({
    'month' : IDL.Text,
    'categoryBreakdown' : IDL.Vec(CategorySummary),
    'totalIncome' : IDL.Float64,
    'totalExpenses' : IDL.Float64,
  });
  
  return IDL.Service({
    '_initializeAccessControl' : IDL.Func([], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'clearBoughtShoppingItems' : IDL.Func([], [], []),
    'createCategory' : IDL.Func([Category], [], []),
    'createExpense' : IDL.Func([Expense], [], []),
    'createShoppingItem' : IDL.Func([ShoppingItem], [], []),
    'deleteBackup' : IDL.Func([IDL.Text], [], []),
    'deleteCategory' : IDL.Func([IDL.Text], [], []),
    'deleteExpense' : IDL.Func([IDL.Text], [], []),
    'deleteExpenseMeta' : IDL.Func([IDL.Text], [], []),
    'deleteShoppingItem' : IDL.Func([IDL.Text], [], []),
    'exportExpenses' : IDL.Func([], [IDL.Vec(Expense)], ['query']),
    'getAppSettings' : IDL.Func([], [IDL.Opt(AppSettings)], ['query']),
    'getBackupsList' : IDL.Func([], [IDL.Vec(BackupRecord)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCategories' : IDL.Func([], [IDL.Vec(Category)], ['query']),
    'getDebts' : IDL.Func([], [IDL.Vec(DebtRecord)], ['query']),
    'getExpenseMetaList' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Text, ExpenseMeta))],
        ['query'],
      ),
    'getExpenses' : IDL.Func([], [IDL.Vec(Expense)], ['query']),
    'getExpensesByCategory' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Expense)],
        ['query'],
      ),
    'getExpensesByMonth' : IDL.Func([IDL.Text], [IDL.Vec(Expense)], ['query']),
    'getIncomeSourcesList' : IDL.Func([], [IDL.Vec(IncomeSource)], ['query']),
    'getMonthlyIncome' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(MonthlyIncome)],
        ['query'],
      ),
    'getMonthlySummary' : IDL.Func([IDL.Text], [MonthlySummary], ['query']),
    'getShoppingItems' : IDL.Func([], [IDL.Vec(ShoppingItem)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'resetUserData' : IDL.Func([], [], []),
    'saveBackup' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'saveDebts' : IDL.Func([IDL.Vec(DebtRecord)], [], []),
    'saveIncomeSources' : IDL.Func([IDL.Vec(IncomeSource)], [], []),
    'setAppSettings' : IDL.Func([AppSettings], [], []),
    'setExpenseMeta' : IDL.Func([IDL.Text, ExpenseMeta], [], []),
    'setMonthlyIncome' : IDL.Func([MonthlyIncome], [], []),
    'toggleShoppingItemBought' : IDL.Func([IDL.Text, IDL.Bool], [], []),
    'updateCategory' : IDL.Func([Category], [], []),
    'updateExpense' : IDL.Func([Expense], [], []),
    'updateShoppingItem' : IDL.Func([ShoppingItem], [], []),
  });
};

export const init = ({ IDL }) => { return []; };