/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface AppSettings {
    updatedAt: bigint;
    currency: string;
    dailyLimit?: number | null;
    weeklyLimit?: number | null;
}
export interface ShoppingItem {
    id: string;
    estimatedPrice?: number;
    date?: string;
    name: string;
    createdAt: bigint;
    bought: boolean;
    category: string;
}
export interface CategorySummary {
    categoryId: string;
    total: number;
    categoryName: string;
}
export interface MonthlySummary {
    month: string;
    categoryBreakdown: Array<CategorySummary>;
    totalIncome: number;
    totalExpenses: number;
}
export interface Expense {
    id: string;
    categoryId: string;
    paymentMethod: string;
    date: string;
    note: string;
    createdAt: bigint;
    amount: number;
    recurring?: boolean | null;
    recurringFrequency?: string | null;
}
export interface MonthlyIncome {
    month: string;
    amount: number;
}
export interface UserProfile {
    name: string;
}
export interface Category {
    id: string;
    name: string;
    color: string;
    budget: number;
    pinned?: boolean | null;
}
export interface IncomeSource {
    id: string;
    name: string;
    color: string;
    monthlyBudget: number;
}
export interface ExpenseMeta {
    tags: string | null;
    receiptUrl: string | null;
}
export interface DebtRecord {
    id: string;
    description: string;
    personName: string;
    amount: number;
    dueDate?: string | null;
    direction: string;
    status: string;
    createdAt: bigint;
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    clearBoughtShoppingItems(): Promise<void>;
    createCategory(category: Category): Promise<void>;
    createExpense(expense: Expense): Promise<void>;
    createShoppingItem(item: ShoppingItem): Promise<void>;
    deleteCategory(categoryId: string): Promise<void>;
    deleteExpense(expenseId: string): Promise<void>;
    deleteShoppingItem(itemId: string): Promise<void>;
    exportExpenses(): Promise<Array<Expense>>;
    getAppSettings(): Promise<AppSettings | null>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getCategories(): Promise<Array<Category>>;
    getExpenses(): Promise<Array<Expense>>;
    getExpensesByCategory(categoryId: string): Promise<Array<Expense>>;
    getExpensesByMonth(month: string): Promise<Array<Expense>>;
    getMonthlyIncome(month: string): Promise<MonthlyIncome | null>;
    getMonthlySummary(month: string): Promise<MonthlySummary>;
    getShoppingItems(): Promise<Array<ShoppingItem>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    resetUserData(): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    getIncomeSourcesList(): Promise<Array<IncomeSource>>;
    saveIncomeSources(sources: Array<IncomeSource>): Promise<void>;
    getExpenseMetaList(): Promise<Array<[string, ExpenseMeta]>>;
    setExpenseMeta(expenseId: string, meta: ExpenseMeta): Promise<void>;
    deleteExpenseMeta(expenseId: string): Promise<void>;
    setAppSettings(settings: AppSettings): Promise<void>;
    setMonthlyIncome(income: MonthlyIncome): Promise<void>;
    toggleShoppingItemBought(itemId: string, bought: boolean): Promise<void>;
    updateCategory(category: Category): Promise<void>;
    updateExpense(expense: Expense): Promise<void>;
    updateShoppingItem(item: ShoppingItem): Promise<void>;
    getDebts(): Promise<Array<DebtRecord>>;
    saveDebts(debts: Array<DebtRecord>): Promise<void>;
}
import type { AppSettings as _AppSettings, IncomeSource as _IncomeSource, MonthlyIncome as _MonthlyIncome, ShoppingItem as _ShoppingItem, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async clearBoughtShoppingItems(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.clearBoughtShoppingItems();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.clearBoughtShoppingItems();
            return result;
        }
    }
    async createCategory(arg0: Category): Promise<void> {
        const candidCat = toCandidCategory(arg0);
        if (this.processError) {
            try {
                const result = await this.actor.createCategory(candidCat);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createCategory(candidCat);
            return result;
        }
    }
    async createExpense(arg0: Expense): Promise<void> {
        const candidExpense = toCandidExpense(arg0);
        if (this.processError) {
            try {
                const result = await this.actor.createExpense(candidExpense);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createExpense(candidExpense);
            return result;
        }
    }
    async createShoppingItem(arg0: ShoppingItem): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createShoppingItem(to_candid_ShoppingItem_n3(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createShoppingItem(to_candid_ShoppingItem_n3(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async deleteCategory(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteCategory(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteCategory(arg0);
            return result;
        }
    }
    async deleteExpense(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteExpense(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteExpense(arg0);
            return result;
        }
    }
    async deleteShoppingItem(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteShoppingItem(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteShoppingItem(arg0);
            return result;
        }
    }
    async exportExpenses(): Promise<Array<Expense>> {
        if (this.processError) {
            try {
                const result = await this.actor.exportExpenses();
                return result.map(fromCandidExpense);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.exportExpenses();
            return result.map(fromCandidExpense);
        }
    }
    async getAppSettings(): Promise<AppSettings | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getAppSettings();
                const raw = result.length === 0 ? null : result[0];
                return raw ? fromCandidAppSettings(raw) : null;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAppSettings();
            const raw = result.length === 0 ? null : result[0];
            return raw ? fromCandidAppSettings(raw) : null;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCategories(): Promise<Array<Category>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCategories();
                return result.map(fromCandidCategory);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCategories();
            return result.map(fromCandidCategory);
        }
    }
    async getExpenses(): Promise<Array<Expense>> {
        if (this.processError) {
            try {
                const result = await this.actor.getExpenses();
                return result.map(fromCandidExpense);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getExpenses();
            return result.map(fromCandidExpense);
        }
    }
    async getExpensesByCategory(arg0: string): Promise<Array<Expense>> {
        if (this.processError) {
            try {
                const result = await this.actor.getExpensesByCategory(arg0);
                return result.map(fromCandidExpense);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getExpensesByCategory(arg0);
            return result.map(fromCandidExpense);
        }
    }
    async getExpensesByMonth(arg0: string): Promise<Array<Expense>> {
        if (this.processError) {
            try {
                const result = await this.actor.getExpensesByMonth(arg0);
                return result.map(fromCandidExpense);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getExpensesByMonth(arg0);
            return result.map(fromCandidExpense);
        }
    }
    async getMonthlyIncome(arg0: string): Promise<MonthlyIncome | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMonthlyIncome(arg0);
                return from_candid_opt_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMonthlyIncome(arg0);
            return from_candid_opt_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMonthlySummary(arg0: string): Promise<MonthlySummary> {
        if (this.processError) {
            try {
                const result = await this.actor.getMonthlySummary(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMonthlySummary(arg0);
            return result;
        }
    }
    async getShoppingItems(): Promise<Array<ShoppingItem>> {
        if (this.processError) {
            try {
                const result = await this.actor.getShoppingItems();
                return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getShoppingItems();
            return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async resetUserData(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.resetUserData();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.resetUserData();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async setAppSettings(arg0: AppSettings): Promise<void> {
        const candidSettings = toCandidAppSettings(arg0);
        if (this.processError) {
            try {
                const result = await this.actor.setAppSettings(candidSettings);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setAppSettings(candidSettings);
            return result;
        }
    }
    async setMonthlyIncome(arg0: MonthlyIncome): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setMonthlyIncome(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setMonthlyIncome(arg0);
            return result;
        }
    }
    async getIncomeSourcesList(): Promise<Array<IncomeSource>> {
        if (this.processError) {
            try {
                const result = await this.actor.getIncomeSourcesList();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getIncomeSourcesList();
            return result;
        }
    }
    async saveIncomeSources(arg0: Array<IncomeSource>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveIncomeSources(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveIncomeSources(arg0);
            return result;
        }
    }
    async getExpenseMetaList(): Promise<Array<[string, ExpenseMeta]>> {
        const result = await (this.actor as any).getExpenseMetaList();
        return (result as Array<[string, { tags: [] | [string]; receiptUrl: [] | [string] }]>).map(
            ([id, meta]) => [
                id,
                {
                    tags: meta.tags.length === 0 ? null : meta.tags[0],
                    receiptUrl: meta.receiptUrl.length === 0 ? null : meta.receiptUrl[0],
                },
            ]
        );
    }
    async setExpenseMeta(expenseId: string, meta: ExpenseMeta): Promise<void> {
        const candidMeta = {
            tags: meta.tags != null ? [meta.tags] : ([] as []),
            receiptUrl: meta.receiptUrl != null ? [meta.receiptUrl] : ([] as []),
        };
        await (this.actor as any).setExpenseMeta(expenseId, candidMeta);
    }
    async deleteExpenseMeta(expenseId: string): Promise<void> {
        await (this.actor as any).deleteExpenseMeta(expenseId);
    }
    async toggleShoppingItemBought(arg0: string, arg1: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.toggleShoppingItemBought(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.toggleShoppingItemBought(arg0, arg1);
            return result;
        }
    }
    async updateCategory(arg0: Category): Promise<void> {
        const candidCat = toCandidCategory(arg0);
        if (this.processError) {
            try {
                const result = await this.actor.updateCategory(candidCat);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateCategory(candidCat);
            return result;
        }
    }
    async updateExpense(arg0: Expense): Promise<void> {
        const candidExpense = toCandidExpense(arg0);
        if (this.processError) {
            try {
                const result = await this.actor.updateExpense(candidExpense);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateExpense(candidExpense);
            return result;
        }
    }
    async updateShoppingItem(arg0: ShoppingItem): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateShoppingItem(to_candid_ShoppingItem_n3(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateShoppingItem(to_candid_ShoppingItem_n3(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async getDebts(): Promise<Array<DebtRecord>> {
        if (this.processError) {
            try {
                const result = await (this.actor as any).getDebts();
                return (result as Array<any>).map(fromCandidDebtRecord);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await (this.actor as any).getDebts();
            return (result as Array<any>).map(fromCandidDebtRecord);
        }
    }
    async saveDebts(arg0: Array<DebtRecord>): Promise<void> {
        const candidDebts = arg0.map(toCandidDebtRecord);
        if (this.processError) {
            try {
                const result = await (this.actor as any).saveDebts(candidDebts);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await (this.actor as any).saveDebts(candidDebts);
            return result;
        }
    }
}
// ── Candid helper functions ──────────────────────────────────────────────────

function toCandidExpense(e: Expense): any {
    return {
        id: e.id,
        categoryId: e.categoryId,
        paymentMethod: e.paymentMethod,
        date: e.date,
        note: e.note,
        createdAt: e.createdAt,
        amount: e.amount,
        recurring: e.recurring != null ? [e.recurring] : [],
        recurringFrequency: e.recurringFrequency != null ? [e.recurringFrequency] : [],
    };
}

function fromCandidExpense(e: any): Expense {
    return {
        id: e.id,
        categoryId: e.categoryId,
        paymentMethod: e.paymentMethod,
        date: e.date,
        note: e.note,
        createdAt: e.createdAt,
        amount: e.amount,
        recurring: e.recurring && e.recurring.length > 0 ? e.recurring[0] : undefined,
        recurringFrequency: e.recurringFrequency && e.recurringFrequency.length > 0 ? e.recurringFrequency[0] : undefined,
    };
}

function toCandidCategory(c: Category): any {
    return {
        id: c.id,
        name: c.name,
        color: c.color,
        budget: c.budget,
        pinned: c.pinned != null ? [c.pinned] : [],
    };
}

function fromCandidCategory(c: any): Category {
    return {
        id: c.id,
        name: c.name,
        color: c.color,
        budget: c.budget,
        pinned: c.pinned && c.pinned.length > 0 ? c.pinned[0] : null,
    };
}

function toCandidAppSettings(s: AppSettings): any {
    return {
        updatedAt: s.updatedAt,
        currency: s.currency,
        dailyLimit: s.dailyLimit != null ? [s.dailyLimit] : [],
        weeklyLimit: s.weeklyLimit != null ? [s.weeklyLimit] : [],
    };
}

function fromCandidAppSettings(s: any): AppSettings {
    return {
        updatedAt: s.updatedAt,
        currency: s.currency,
        dailyLimit: s.dailyLimit && s.dailyLimit.length > 0 ? s.dailyLimit[0] : null,
        weeklyLimit: s.weeklyLimit && s.weeklyLimit.length > 0 ? s.weeklyLimit[0] : null,
    };
}

function toCandidDebtRecord(d: DebtRecord): any {
    return {
        id: d.id,
        description: d.description,
        personName: d.personName,
        amount: d.amount,
        dueDate: d.dueDate != null ? [d.dueDate] : [],
        direction: d.direction,
        status: d.status,
        createdAt: d.createdAt,
    };
}

function fromCandidDebtRecord(d: any): DebtRecord {
    return {
        id: d.id,
        description: d.description,
        personName: d.personName,
        amount: d.amount,
        dueDate: d.dueDate && d.dueDate.length > 0 ? d.dueDate[0] : null,
        direction: d.direction,
        status: d.status,
        createdAt: d.createdAt,
    };
}

function from_candid_ShoppingItem_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ShoppingItem): ShoppingItem {
    return from_candid_record_n12(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n8(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [number]): number | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_AppSettings]): AppSettings | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_MonthlyIncome]): MonthlyIncome | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    estimatedPrice: [] | [number];
    date: [] | [string];
    name: string;
    createdAt: bigint;
    bought: boolean;
    category: string;
}): {
    id: string;
    estimatedPrice?: number;
    date?: string;
    name: string;
    createdAt: bigint;
    bought: boolean;
    category: string;
} {
    return {
        id: value.id,
        estimatedPrice: record_opt_to_undefined(from_candid_opt_n13(_uploadFile, _downloadFile, value.estimatedPrice)),
        date: record_opt_to_undefined(from_candid_opt_n14(_uploadFile, _downloadFile, value.date)),
        name: value.name,
        createdAt: value.createdAt,
        bought: value.bought,
        category: value.category
    };
}
function from_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ShoppingItem>): Array<ShoppingItem> {
    return value.map((x)=>from_candid_ShoppingItem_n11(_uploadFile, _downloadFile, x));
}
function to_candid_ShoppingItem_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ShoppingItem): _ShoppingItem {
    return to_candid_record_n4(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_record_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    estimatedPrice?: number;
    date?: string;
    name: string;
    createdAt: bigint;
    bought: boolean;
    category: string;
}): {
    id: string;
    estimatedPrice: [] | [number];
    date: [] | [string];
    name: string;
    createdAt: bigint;
    bought: boolean;
    category: string;
} {
    return {
        id: value.id,
        estimatedPrice: value.estimatedPrice ? candid_some(value.estimatedPrice) : candid_none(),
        date: value.date ? candid_some(value.date) : candid_none(),
        name: value.name,
        createdAt: value.createdAt,
        bought: value.bought,
        category: value.category
    };
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
