/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Category {
    id: string;
    name: string;
    color: string;
    pinned?: boolean;
    budget: number;
}
export interface IncomeSource {
    id: string;
    monthlyBudget: number;
    name: string;
    color: string;
}
export interface BackupRecord {
    data: string;
    name: string;
    createdAt: bigint;
}
export interface ShoppingItem {
    id: string;
    estimatedPrice?: number;
    date?: string;
    name: string;
    createdAt: bigint;
    bought: boolean;
    category: string;
}
export interface AppSettings {
    dailyLimit?: number;
    updatedAt: bigint;
    currency: string;
    weeklyLimit?: number;
}
export interface ExpenseMeta {
    receiptUrl?: string;
    tags?: string;
}
export interface CategorySummary {
    categoryId: string;
    total: number;
    categoryName: string;
}
export interface MonthlySummary {
    month: string;
    categoryBreakdown: Array<CategorySummary>;
    totalIncome: number;
    totalExpenses: number;
}
export interface Expense {
    id: string;
    categoryId: string;
    paymentMethod: string;
    date: string;
    note: string;
    createdAt: bigint;
    amount: number;
}
export interface MonthlyIncome {
    month: string;
    amount: number;
}
export interface UserProfile {
    name: string;
}
export interface DebtRecord {
    id: string;
    status: string;
    direction: string;
    createdAt: bigint;
    dueDate?: string;
    description: string;
    personName: string;
    amount: number;
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControl(): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    clearBoughtShoppingItems(): Promise<void>;
    createCategory(category: Category): Promise<void>;
    createExpense(expense: Expense): Promise<void>;
    createShoppingItem(item: ShoppingItem): Promise<void>;
    deleteBackup(name: string): Promise<void>;
    deleteCategory(categoryId: string): Promise<void>;
    deleteExpense(expenseId: string): Promise<void>;
    deleteExpenseMeta(expenseId: string): Promise<void>;
    deleteShoppingItem(itemId: string): Promise<void>;
    exportExpenses(): Promise<Array<Expense>>;
    getAppSettings(): Promise<AppSettings | null>;
    getBackupsList(): Promise<Array<BackupRecord>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getCategories(): Promise<Array<Category>>;
    getDebts(): Promise<Array<DebtRecord>>;
    getExpenseMetaList(): Promise<Array<[string, ExpenseMeta]>>;
    getExpenses(): Promise<Array<Expense>>;
    getExpensesByCategory(categoryId: string): Promise<Array<Expense>>;
    getExpensesByMonth(month: string): Promise<Array<Expense>>;
    getIncomeSourcesList(): Promise<Array<IncomeSource>>;
    getMonthlyIncome(month: string): Promise<MonthlyIncome | null>;
    getMonthlySummary(month: string): Promise<MonthlySummary>;
    getShoppingItems(): Promise<Array<ShoppingItem>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    resetUserData(): Promise<void>;
    saveBackup(name: string, data: string): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    saveDebts(debts: Array<DebtRecord>): Promise<void>;
    saveIncomeSources(sources: Array<IncomeSource>): Promise<void>;
    setAppSettings(settings: AppSettings): Promise<void>;
    setExpenseMeta(expenseId: string, meta: ExpenseMeta): Promise<void>;
    setMonthlyIncome(income: MonthlyIncome): Promise<void>;
    toggleShoppingItemBought(itemId: string, bought: boolean): Promise<void>;
    updateCategory(category: Category): Promise<void>;
    updateExpense(expense: Expense): Promise<void>;
    updateShoppingItem(item: ShoppingItem): Promise<void>;
}
import type { AppSettings as _AppSettings, Category as _Category, DebtRecord as _DebtRecord, ExpenseMeta as _ExpenseMeta, MonthlyIncome as _MonthlyIncome, ShoppingItem as _ShoppingItem, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControl(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControl();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControl();
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async clearBoughtShoppingItems(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.clearBoughtShoppingItems();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.clearBoughtShoppingItems();
            return result;
        }
    }
    async createCategory(arg0: Category): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createCategory(to_candid_Category_n3(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createCategory(to_candid_Category_n3(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async createExpense(arg0: Expense): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createExpense(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createExpense(arg0);
            return result;
        }
    }
    async createShoppingItem(arg0: ShoppingItem): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createShoppingItem(to_candid_ShoppingItem_n5(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createShoppingItem(to_candid_ShoppingItem_n5(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async deleteBackup(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteBackup(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteBackup(arg0);
            return result;
        }
    }
    async deleteCategory(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteCategory(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteCategory(arg0);
            return result;
        }
    }
    async deleteExpense(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteExpense(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteExpense(arg0);
            return result;
        }
    }
    async deleteExpenseMeta(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteExpenseMeta(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteExpenseMeta(arg0);
            return result;
        }
    }
    async deleteShoppingItem(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteShoppingItem(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteShoppingItem(arg0);
            return result;
        }
    }
    async exportExpenses(): Promise<Array<Expense>> {
        if (this.processError) {
            try {
                const result = await this.actor.exportExpenses();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.exportExpenses();
            return result;
        }
    }
    async getAppSettings(): Promise<AppSettings | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getAppSettings();
                return from_candid_opt_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAppSettings();
            return from_candid_opt_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async getBackupsList(): Promise<Array<BackupRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getBackupsList();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBackupsList();
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCategories(): Promise<Array<Category>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCategories();
                return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCategories();
            return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDebts(): Promise<Array<DebtRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getDebts();
                return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDebts();
            return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getExpenseMetaList(): Promise<Array<[string, ExpenseMeta]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getExpenseMetaList();
                return from_candid_vec_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getExpenseMetaList();
            return from_candid_vec_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async getExpenses(): Promise<Array<Expense>> {
        if (this.processError) {
            try {
                const result = await this.actor.getExpenses();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getExpenses();
            return result;
        }
    }
    async getExpensesByCategory(arg0: string): Promise<Array<Expense>> {
        if (this.processError) {
            try {
                const result = await this.actor.getExpensesByCategory(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getExpensesByCategory(arg0);
            return result;
        }
    }
    async getExpensesByMonth(arg0: string): Promise<Array<Expense>> {
        if (this.processError) {
            try {
                const result = await this.actor.getExpensesByMonth(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getExpensesByMonth(arg0);
            return result;
        }
    }
    async getIncomeSourcesList(): Promise<Array<IncomeSource>> {
        if (this.processError) {
            try {
                const result = await this.actor.getIncomeSourcesList();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getIncomeSourcesList();
            return result;
        }
    }
    async getMonthlyIncome(arg0: string): Promise<MonthlyIncome | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMonthlyIncome(arg0);
                return from_candid_opt_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMonthlyIncome(arg0);
            return from_candid_opt_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMonthlySummary(arg0: string): Promise<MonthlySummary> {
        if (this.processError) {
            try {
                const result = await this.actor.getMonthlySummary(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMonthlySummary(arg0);
            return result;
        }
    }
    async getShoppingItems(): Promise<Array<ShoppingItem>> {
        if (this.processError) {
            try {
                const result = await this.actor.getShoppingItems();
                return from_candid_vec_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getShoppingItems();
            return from_candid_vec_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async resetUserData(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.resetUserData();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.resetUserData();
            return result;
        }
    }
    async saveBackup(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveBackup(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveBackup(arg0, arg1);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async saveDebts(arg0: Array<DebtRecord>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveDebts(to_candid_vec_n30(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveDebts(to_candid_vec_n30(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async saveIncomeSources(arg0: Array<IncomeSource>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveIncomeSources(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveIncomeSources(arg0);
            return result;
        }
    }
    async setAppSettings(arg0: AppSettings): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setAppSettings(to_candid_AppSettings_n33(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setAppSettings(to_candid_AppSettings_n33(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async setExpenseMeta(arg0: string, arg1: ExpenseMeta): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setExpenseMeta(arg0, to_candid_ExpenseMeta_n35(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setExpenseMeta(arg0, to_candid_ExpenseMeta_n35(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async setMonthlyIncome(arg0: MonthlyIncome): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setMonthlyIncome(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setMonthlyIncome(arg0);
            return result;
        }
    }
    async toggleShoppingItemBought(arg0: string, arg1: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.toggleShoppingItemBought(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.toggleShoppingItemBought(arg0, arg1);
            return result;
        }
    }
    async updateCategory(arg0: Category): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateCategory(to_candid_Category_n3(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateCategory(to_candid_Category_n3(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updateExpense(arg0: Expense): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateExpense(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateExpense(arg0);
            return result;
        }
    }
    async updateShoppingItem(arg0: ShoppingItem): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateShoppingItem(to_candid_ShoppingItem_n5(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateShoppingItem(to_candid_ShoppingItem_n5(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
}
function from_candid_AppSettings_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AppSettings): AppSettings {
    return from_candid_record_n9(_uploadFile, _downloadFile, value);
}
function from_candid_Category_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Category): Category {
    return from_candid_record_n16(_uploadFile, _downloadFile, value);
}
function from_candid_DebtRecord_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DebtRecord): DebtRecord {
    return from_candid_record_n20(_uploadFile, _downloadFile, value);
}
function from_candid_ExpenseMeta_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExpenseMeta): ExpenseMeta {
    return from_candid_record_n25(_uploadFile, _downloadFile, value);
}
function from_candid_ShoppingItem_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ShoppingItem): ShoppingItem {
    return from_candid_record_n29(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n13(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [number]): number | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_MonthlyIncome]): MonthlyIncome | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_AppSettings]): AppSettings | null {
    return value.length === 0 ? null : from_candid_AppSettings_n8(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    name: string;
    color: string;
    pinned: [] | [boolean];
    budget: number;
}): {
    id: string;
    name: string;
    color: string;
    pinned?: boolean;
    budget: number;
} {
    return {
        id: value.id,
        name: value.name,
        color: value.color,
        pinned: record_opt_to_undefined(from_candid_opt_n17(_uploadFile, _downloadFile, value.pinned)),
        budget: value.budget
    };
}
function from_candid_record_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: string;
    direction: string;
    createdAt: bigint;
    dueDate: [] | [string];
    description: string;
    personName: string;
    amount: number;
}): {
    id: string;
    status: string;
    direction: string;
    createdAt: bigint;
    dueDate?: string;
    description: string;
    personName: string;
    amount: number;
} {
    return {
        id: value.id,
        status: value.status,
        direction: value.direction,
        createdAt: value.createdAt,
        dueDate: record_opt_to_undefined(from_candid_opt_n21(_uploadFile, _downloadFile, value.dueDate)),
        description: value.description,
        personName: value.personName,
        amount: value.amount
    };
}
function from_candid_record_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    receiptUrl: [] | [string];
    tags: [] | [string];
}): {
    receiptUrl?: string;
    tags?: string;
} {
    return {
        receiptUrl: record_opt_to_undefined(from_candid_opt_n21(_uploadFile, _downloadFile, value.receiptUrl)),
        tags: record_opt_to_undefined(from_candid_opt_n21(_uploadFile, _downloadFile, value.tags))
    };
}
function from_candid_record_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    estimatedPrice: [] | [number];
    date: [] | [string];
    name: string;
    createdAt: bigint;
    bought: boolean;
    category: string;
}): {
    id: string;
    estimatedPrice?: number;
    date?: string;
    name: string;
    createdAt: bigint;
    bought: boolean;
    category: string;
} {
    return {
        id: value.id,
        estimatedPrice: record_opt_to_undefined(from_candid_opt_n10(_uploadFile, _downloadFile, value.estimatedPrice)),
        date: record_opt_to_undefined(from_candid_opt_n21(_uploadFile, _downloadFile, value.date)),
        name: value.name,
        createdAt: value.createdAt,
        bought: value.bought,
        category: value.category
    };
}
function from_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    dailyLimit: [] | [number];
    updatedAt: bigint;
    currency: string;
    weeklyLimit: [] | [number];
}): {
    dailyLimit?: number;
    updatedAt: bigint;
    currency: string;
    weeklyLimit?: number;
} {
    return {
        dailyLimit: record_opt_to_undefined(from_candid_opt_n10(_uploadFile, _downloadFile, value.dailyLimit)),
        updatedAt: value.updatedAt,
        currency: value.currency,
        weeklyLimit: record_opt_to_undefined(from_candid_opt_n10(_uploadFile, _downloadFile, value.weeklyLimit))
    };
}
function from_candid_tuple_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [string, _ExpenseMeta]): [string, ExpenseMeta] {
    return [
        value[0],
        from_candid_ExpenseMeta_n24(_uploadFile, _downloadFile, value[1])
    ];
}
function from_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Category>): Array<Category> {
    return value.map((x)=>from_candid_Category_n15(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_DebtRecord>): Array<DebtRecord> {
    return value.map((x)=>from_candid_DebtRecord_n19(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<[string, _ExpenseMeta]>): Array<[string, ExpenseMeta]> {
    return value.map((x)=>from_candid_tuple_n23(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ShoppingItem>): Array<ShoppingItem> {
    return value.map((x)=>from_candid_ShoppingItem_n28(_uploadFile, _downloadFile, x));
}
function to_candid_AppSettings_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AppSettings): _AppSettings {
    return to_candid_record_n34(_uploadFile, _downloadFile, value);
}
function to_candid_Category_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Category): _Category {
    return to_candid_record_n4(_uploadFile, _downloadFile, value);
}
function to_candid_DebtRecord_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DebtRecord): _DebtRecord {
    return to_candid_record_n32(_uploadFile, _downloadFile, value);
}
function to_candid_ExpenseMeta_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExpenseMeta): _ExpenseMeta {
    return to_candid_record_n36(_uploadFile, _downloadFile, value);
}
function to_candid_ShoppingItem_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ShoppingItem): _ShoppingItem {
    return to_candid_record_n6(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_record_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: string;
    direction: string;
    createdAt: bigint;
    dueDate?: string;
    description: string;
    personName: string;
    amount: number;
}): {
    id: string;
    status: string;
    direction: string;
    createdAt: bigint;
    dueDate: [] | [string];
    description: string;
    personName: string;
    amount: number;
} {
    return {
        id: value.id,
        status: value.status,
        direction: value.direction,
        createdAt: value.createdAt,
        dueDate: value.dueDate ? candid_some(value.dueDate) : candid_none(),
        description: value.description,
        personName: value.personName,
        amount: value.amount
    };
}
function to_candid_record_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    dailyLimit?: number;
    updatedAt: bigint;
    currency: string;
    weeklyLimit?: number;
}): {
    dailyLimit: [] | [number];
    updatedAt: bigint;
    currency: string;
    weeklyLimit: [] | [number];
} {
    return {
        dailyLimit: value.dailyLimit ? candid_some(value.dailyLimit) : candid_none(),
        updatedAt: value.updatedAt,
        currency: value.currency,
        weeklyLimit: value.weeklyLimit ? candid_some(value.weeklyLimit) : candid_none()
    };
}
function to_candid_record_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    receiptUrl?: string;
    tags?: string;
}): {
    receiptUrl: [] | [string];
    tags: [] | [string];
} {
    return {
        receiptUrl: value.receiptUrl ? candid_some(value.receiptUrl) : candid_none(),
        tags: value.tags ? candid_some(value.tags) : candid_none()
    };
}
function to_candid_record_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    name: string;
    color: string;
    pinned?: boolean;
    budget: number;
}): {
    id: string;
    name: string;
    color: string;
    pinned: [] | [boolean];
    budget: number;
} {
    return {
        id: value.id,
        name: value.name,
        color: value.color,
        pinned: value.pinned ? candid_some(value.pinned) : candid_none(),
        budget: value.budget
    };
}
function to_candid_record_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    estimatedPrice?: number;
    date?: string;
    name: string;
    createdAt: bigint;
    bought: boolean;
    category: string;
}): {
    id: string;
    estimatedPrice: [] | [number];
    date: [] | [string];
    name: string;
    createdAt: bigint;
    bought: boolean;
    category: string;
} {
    return {
        id: value.id,
        estimatedPrice: value.estimatedPrice ? candid_some(value.estimatedPrice) : candid_none(),
        date: value.date ? candid_some(value.date) : candid_none(),
        name: value.name,
        createdAt: value.createdAt,
        bought: value.bought,
        category: value.category
    };
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_vec_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<DebtRecord>): Array<_DebtRecord> {
    return value.map((x)=>to_candid_DebtRecord_n31(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
